Updade: Integrations navigator 0.3.1 - lib: PWM: Add set_pwm_channels_duty_cycle for Python and C
bluerobotics/navigator-lib pull request #63
Opened 2024-03-01 18:41 UTC by RaulTrombin

2024-03-01 20:10 UTC, joaoantoniocardoso approved these changes

2024-03-04 11:34 UTC, patrickelectric approved these changes

2024-03-04 11:36 UTC, patrickelectric requested changes

2024-03-04 11:36 UTC, patrickelectric commented on src/lib.rs
> +    for i in 0..channels.len() {
wait, why not iterating over the vector ?>\
```suggestion
    for channel in channels {
```
?

2024-03-04 12:09 UTC, merged